-- MySQL Script generated by MySQL Workbench
-- Sun Jun  4 20:19:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_userData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_userData` (
  `user_id` INT NOT NULL,
  `userData_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `userData_id`),
  INDEX `fk_user_has_userData_userData1_idx` (`userData_id` ASC) VISIBLE,
  INDEX `fk_user_has_userData_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `userData_id_UNIQUE` (`userData_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_userData_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_userData_userData1`
    FOREIGN KEY (`userData_id`)
    REFERENCES `mydb`.`userData` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group_has_groupData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group_has_groupData` (
  `Group_id` INT NOT NULL,
  `groupData_id` INT NOT NULL,
  PRIMARY KEY (`Group_id`, `groupData_id`),
  INDEX `fk_Group_has_groupData_groupData1_idx` (`groupData_id` ASC) VISIBLE,
  INDEX `fk_Group_has_groupData_Group1_idx` (`Group_id` ASC) VISIBLE,
  UNIQUE INDEX `Group_id_UNIQUE` (`Group_id` ASC) VISIBLE,
  UNIQUE INDEX `groupData_id_UNIQUE` (`groupData_id` ASC) VISIBLE,
  CONSTRAINT `fk_Group_has_groupData_Group1`
    FOREIGN KEY (`Group_id`)
    REFERENCES `mydb`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_has_groupData_groupData1`
    FOREIGN KEY (`groupData_id`)
    REFERENCES `mydb`.`groupData` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_Group` (
  `user_id` INT NOT NULL,
  `Group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `Group_id`),
  INDEX `fk_user_has_Group_Group1_idx` (`Group_id` ASC) VISIBLE,
  INDEX `fk_user_has_Group_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_Group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Group_Group1`
    FOREIGN KEY (`Group_id`)
    REFERENCES `mydb`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `managmentLevel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group_has_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group_has_access` (
  `Group_id` INT NOT NULL,
  `access_id` INT NOT NULL,
  PRIMARY KEY (`Group_id`, `access_id`),
  INDEX `fk_Group_has_access_access1_idx` (`access_id` ASC) VISIBLE,
  INDEX `fk_Group_has_access_Group1_idx` (`Group_id` ASC) VISIBLE,
  CONSTRAINT `fk_Group_has_access_Group1`
    FOREIGN KEY (`Group_id`)
    REFERENCES `mydb`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_has_access_access1`
    FOREIGN KEY (`access_id`)
    REFERENCES `mydb`.`access` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`access_has_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`access_has_resource` (
  `access_id` INT NOT NULL,
  `resource_id` INT NOT NULL,
  PRIMARY KEY (`access_id`, `resource_id`),
  INDEX `fk_access_has_resource_resource1_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_access_has_resource_access1_idx` (`access_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_has_resource_access1`
    FOREIGN KEY (`access_id`)
    REFERENCES `mydb`.`access` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_has_resource_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `mydb`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
